"""Regenerate the docs pages that come from the tool itself.

    python scripts/gen_docs.py          # write them
    python scripts/gen_docs.py --check  # exit 1 if any is stale (CI and tests run this)

Writes docs/vocabulary.md, docs/cli.md and one SVG per example page in docs/assets/examples/.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from glyph_cli import Vocabulary
from glyph_cli.cli import build_parser
from glyph_cli.drawing import render, render_svg
from glyph_cli.export import vocabulary_markdown
from glyph_cli.page import parse_page

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
NOTE = "<!-- generated by scripts/gen_docs.py from the glyph --help output; do not edit -->"


def cli_markdown() -> str:
    os.environ["COLUMNS"] = "100"  # argparse wraps help to the terminal width
    parser = build_parser()
    out = ["# Command reference", "", NOTE, "", "```text", "$ glyph --help", parser.format_help().rstrip(), "```"]
    sub = next(a for a in parser._actions if a.dest == "cmd")
    for name, p in sub.choices.items():
        out += ["", f"## `glyph {name}`", "", "```text", f"$ glyph {name} --help", p.format_help().rstrip(), "```"]
    return "\n".join(out) + "\n"


def parts_text(vocab: Vocabulary) -> str:
    """The 15 parts drawn in rows of five, with their names above."""
    names = list(vocab.parts)
    blocks = []
    for i in range(0, len(names), 5):
        row = names[i : i + 5]
        lines = ["".join(f"{n:<10}" for n in row).rstrip()]
        for r in range(3):
            lines.append("".join(f"{vocab.parts[n].shape[r]:<10}" for n in row).rstrip())
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


def outputs() -> dict[Path, str]:
    vocab = Vocabulary.load()
    files = {
        DOCS / "vocabulary.md": vocabulary_markdown(vocab, "Vocabulary"),
        DOCS / "cli.md": cli_markdown(),
        DOCS / "assets" / "parts.txt": parts_text(vocab),
    }
    for src in sorted((ROOT / "examples").glob("*.txt")):
        page = parse_page(src.read_text(encoding="utf-8"), vocab)
        files[DOCS / "assets" / "examples" / f"{src.stem}.svg"] = render_svg(vocab, page)
        files[DOCS / "assets" / "examples" / f"{src.stem}.drawing.txt"] = "\n".join(render(vocab, page)) + "\n"
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    stale = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if a.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    for p in stale:
        print(f"stale: {p} (run python scripts/gen_docs.py)", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
