"""The vocabulary as a Markdown document."""

from __future__ import annotations

from .drawing import band_rows
from .script import Vocabulary

HEADER = "<!-- generated by `glyph export-md`; edit the vocabulary with the tool, not this file -->"

INTRO = """\
How words are made: a **kind** part narrowed by a **which** part (`KIND.WHICH`). A single part is a word
on its own. Any part can also be a **relation**, and numbers (`ONE.0` to `ONE.511`) are built in, so they
are not listed. Status: **preliminary**, {count} words."""


def vocabulary_markdown(vocab: Vocabulary, title: str | None = None) -> str:
    out = []
    if title:
        out += [f"# {title}", "", INTRO.format(count=len(vocab.entries)), ""]
    out.append(HEADER)
    for domain in vocab.domains():
        out += ["", f"### {domain}", "", "| Word | Parts | Meaning | Note |", "|---|---|---|---|"]
        for e in vocab.entries:
            if e.domain != domain:
                continue
            pic = "<br>".join(f"`{r}`" for r in band_rows(vocab, list(e.word.halves), "+"))
            out.append(f"| {pic} | {e.word} | {e.gloss} | {e.note} |")
    return "\n".join(out) + "\n"
